# Generated by Django 2.2 on 2021-02-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
